python synthetic_powerlaw_main.py --emb_dim 10
python synthetic_powerlaw_main.py --emb_dim 20
python synthetic_powerlaw_main.py --emb_dim 30
python synthetic_powerlaw_main.py --emb_dim 40
python synthetic_powerlaw_main.py --emb_dim 50
python synthetic_powerlaw_main.py --emb_dim 60
python synthetic_powerlaw_main.py --emb_dim 70
python synthetic_powerlaw_main.py --emb_dim 80
python synthetic_powerlaw_main.py --emb_dim 90
python synthetic_powerlaw_main.py --emb_dim 100
